# Generated by Django 6.0.4 on 2026-04-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('tutor', 'Tuteur'), ('both', 'Étudiant et tuteur'), ('admin', 'Administrateur')], default='student', max_length=20),
        ),
    ]
