# Generated by Django 6.0.4 on 2026-04-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_role_both'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePropose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2'), ('Doctorat', 'Doctorat')], max_length=20)),
                ('filiere_cible', models.CharField(default='Informatique', max_length=120, verbose_name='filière')),
                ('format_seance', models.CharField(choices=[('Online', 'En ligne'), ('Présentiel', 'Présentiel')], default='Online', max_length=20)),
                ('planning', models.CharField(blank=True, max_length=255, verbose_name='planning (texte)')),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('published', 'Publié'), ('pending', 'En attente')], default='published', max_length=20)),
                ('creneaux', models.JSONField(blank=True, default=list)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_proposes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'module proposé',
                'verbose_name_plural': 'modules proposés',
                'ordering': ['niveau', 'titre'],
            },
        ),
    ]
