# Generated by Django 6.0.4 on 2026-04-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_module_propose'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepropose',
            name='description',
            field=models.TextField(blank=True, verbose_name='description du cours'),
        ),
        migrations.AddField(
            model_name='modulepropose',
            name='duree_label',
            field=models.CharField(blank=True, max_length=20, verbose_name='durée affichée'),
        ),
        migrations.AddField(
            model_name='modulepropose',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
