# Generated by Django 6.0.4 on 2026-04-11 10:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_module_propose_description_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_titre', models.CharField(max_length=220, verbose_name='module (libellé)')),
                ('date_label', models.CharField(blank=True, max_length=64, verbose_name='date affichée')),
                ('creneau_label', models.CharField(blank=True, max_length=160, verbose_name='créneau affiché')),
                ('duree_heures', models.DecimalField(decimal_places=2, default=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24)])),
                ('format_seance', models.CharField(choices=[('Online', 'En ligne'), ('Présentiel', 'Présentiel')], default='Online', max_length=20)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('completed', 'Complétée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('student_session_confirm', models.BooleanField(default=False)),
                ('tutor_session_confirm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_comme_etudiant', to=settings.AUTH_USER_MODEL)),
                ('module_propose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='accounts.modulepropose')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_comme_tuteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
