# Generated by Django 6.0.4 on 2026-04-11 11:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutor_review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre d’avis tuteur (séances évaluées)'),
        ),
        migrations.CreateModel(
            name='EvaluationSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_donnees', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='accounts.reservation')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'évaluation de séance',
                'verbose_name_plural': 'évaluations de séance',
                'ordering': ['-created_at'],
            },
        ),
    ]
