# Generated by Django 6.0.4 on 2026-04-16 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_tutor_review_count_evaluationseance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_auteur', models.CharField(help_text='student ou tutor', max_length=20)),
                ('code_motif', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_emis', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='accounts.reservation')),
            ],
            options={
                'verbose_name': 'signalement de séance',
                'verbose_name_plural': 'signalements de séance',
                'ordering': ['-created_at'],
            },
        ),
    ]
