# Generated by Django 5.2.13 on 2026-04-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(
                default=True, verbose_name="peut utiliser l’espace étudiant"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_tutor",
            field=models.BooleanField(
                default=True, verbose_name="peut utiliser l’espace tuteur"
            ),
        ),
    ]
