# Generated by Django 6.0.4 on 2026-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_user_role_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="meet_url",
            field=models.URLField(
                blank=True,
                help_text="Lien https collé par le tuteur (visioconférence hors WebRTC).",
                max_length=500,
                null=True,
                verbose_name="lien Google Meet",
            ),
        ),
    ]
