# Generated by Django 6.0.4 on 2026-04-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_reservation_meet_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="meet_url",
            field=models.URLField(
                blank=True,
                help_text="Lien https collé par le tuteur (visioconférence hors WebRTC).",
                max_length=500,
                null=True,
                verbose_name="lien visio",
            ),
        ),
    ]
