# Generated by Django 6.0.4 on 2026-04-17 15:39

from django.db import migrations, models


def _migrate_in_progress_to_confirmed(apps, schema_editor):
    Reservation = apps.get_model("accounts", "Reservation")
    Reservation.objects.filter(statut="in_progress").update(statut="confirmed")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_reservation_meet_url_verbose"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="creneau_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Identifiant du créneau dans le module (évite les doublons d’affichage).",
                max_length=120,
                verbose_name="réf. créneau",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="slot_end",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="fin créneau"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="slot_start",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="début créneau"
            ),
        ),
        migrations.RunPython(_migrate_in_progress_to_confirmed, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="reservation",
            name="meet_url",
            field=models.URLField(
                blank=True,
                help_text="Lien https (Meet, Zoom, Teams, etc.) fourni par le tuteur.",
                max_length=500,
                null=True,
                verbose_name="lien visio",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("confirmed", "Confirmée"),
                    ("completed", "Complétée"),
                    ("cancelled", "Annulée"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
