from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AvisPublicTuteurView,
    ConnexionView,
    DetailModuleView,
    EtudiantReservationAnnulerView,
    EtudiantReservationsView,
    EvaluationSeanceCreateView,
    EvaluationsRecuesTuteurView,
    InscriptionView,
    ListeEtudiantsView,
    ListeModulesView,
    ListeTuteursView,
    MesSeancesEtudiantView,
    MesTuteursEtudiantView,
    MoiView,
    SeanceAccepterTuteurView,
    SeanceConfirmerFinView,
    SeanceDetailView,
    SeanceMeetUrlView,
    ModulesPubliesTuteurView,
    TuteurModuleDetailView,
    TuteurModulesView,
    TuteurReservationsRecuesView,
)

urlpatterns = [
    path("inscription/", InscriptionView.as_view(), name="inscription"),
    path("connexion/", ConnexionView.as_view(), name="connexion"),
    path("modules/", ListeModulesView.as_view(), name="liste-modules"),
    path("modules/<int:pk>/", DetailModuleView.as_view(), name="detail-module"),
    path("tuteur/modules/", TuteurModulesView.as_view(), name="tuteur-modules"),
    path("tuteurs/modules/", TuteurModulesView.as_view(), name="tuteurs-modules-alias"),
    path("tuteur/modules/<int:pk>/", TuteurModuleDetailView.as_view(), name="tuteur-module-detail"),
    path("etudiants/", ListeEtudiantsView.as_view(), name="liste-etudiants"),
    path("etudiant/mes-tuteurs/", MesTuteursEtudiantView.as_view(), name="mes-tuteurs-etudiant"),
    path("etudiant/reservations/", EtudiantReservationsView.as_view(), name="etudiant-reservations"),
    path(
        "etudiant/reservations/<int:pk>/annuler/",
        EtudiantReservationAnnulerView.as_view(),
        name="etudiant-reservation-annuler",
    ),
    path("tuteur/reservations-recues/", TuteurReservationsRecuesView.as_view(), name="tuteur-reservations-recues"),
    path("tuteurs/<int:pk>/modules/", ModulesPubliesTuteurView.as_view(), name="tuteur-modules-publies"),
    path("tuteurs/<int:pk>/avis/", AvisPublicTuteurView.as_view(), name="tuteur-avis-public"),
    path("tuteurs/", ListeTuteursView.as_view(), name="liste-tuteurs"),
    path("evaluations/", EvaluationSeanceCreateView.as_view(), name="evaluations-create"),
    path("tuteur/evaluations-recues/", EvaluationsRecuesTuteurView.as_view(), name="tuteur-evaluations-recues"),
    path("auth/me/", MoiView.as_view(), name="auth-me"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="auth-refresh"),
    path("seances/<int:pk>/accepter-tuteur/", SeanceAccepterTuteurView.as_view(), name="seance-accepter-tuteur"),
    path("seances/<int:pk>/confirmer-fin/", SeanceConfirmerFinView.as_view(), name="seance-confirmer-fin"),
    path("seances/<int:pk>/meet-url/", SeanceMeetUrlView.as_view(), name="seance-meet-url"),
    path("seances/<int:pk>/", SeanceDetailView.as_view(), name="seance-detail"),
    path("seances/", MesSeancesEtudiantView.as_view(), name="seances-etudiant"),
]
